aparatos/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from .sitemap import AparatosSitemap


app_name = 'aparatos'

sitemaps ={
    'aparatos': AparatosSitemap,
    }

urlpatterns = [
    path('lista/', views.ListaAparatos.as_view(), name='aparatos_lista'),
    path('producto-detalle/<slug:slug>', views.DetalleAparatos.as_view(), name='aparatos_detalle'),
    path('modelo-detalle/<slug:slug>', views.DetalleModelo.as_view(), name='modelo_detalle'),
]

core/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from .sitemap import RecetasSitemap
from aparatos.sitemap import AparatosSitemap

app_name = 'core'

sitemaps ={
    'recetas': RecetasSitemap,
    'aparatos': AparatosSitemap,
    }

urlpatterns = [
    path('', views.home, name='home'),
    path('receta_detalle/<slug:slug>/', views.VistaDetalle.as_view(), name='recetas'),
    path('search/', views.receta_search, name='receta_search'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    path('listado-recetas/', views.VistaLista.as_view(), name='receta_lista'),
    path('terminos-de-uso/', views.TermsOfUseView.as_view(), name='terms_of_use'),
    path('politica-de-privacidad/', views.PrivacidadView.as_view(), name='privacy_policy'),
    path('favorito/agregar/<int:receta_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('favorito/eliminar/<int:receta_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
]

recetas_lukas/urls.py
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from aparatos.sitemap import AparatosSitemap
from core.sitemap import RecetasSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'aparatos': AparatosSitemap,
    'recetas': RecetasSitemap,
}

# # Ensure users go through the allauth workflow when logging into admin.
# admin.site.login = staff_member_required(admin.site.login, login_url='/accounts/login')
# # Run the standard admin set-up.
# admin.autodiscover()

urlpatterns = [
    path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('aparatos/', include('aparatos.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('core.urls')),
    path('', include('django_prometheus.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/page/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="format-detection" content="telephone=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="author" content="Egoitz Abilleira">
  <meta name="description" content="Blog de recetas">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-NGQB2FGB');</script>
  <!-- End Google Tag Manager -->
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2535476345777598"
     crossorigin="anonymous"></script>
  <!-- Aos for animations -->
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js" defer></script>
  <!-- End Aos for animations -->
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
  <script src="{% static 'js/scripts.js' %}"></script>
  <!-- Biblioteca de Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% block extrahead %}{% endblock extrahead %}
</head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BK0MXMM6CW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BK0MXMM6CW');
</script>

    <body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NGQB2FGB"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js" defer></script>
        <script type="text/javascript">
            var autocompleteUrl = "{% url 'core:autocomplete' %}";
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        {% block header %}{% endblock header %}
        {% block content %}{% endblock content %}
        {% block footer %}{% endblock footer %}
        {% block javascript %}
        {% endblock javascript %}
    </body>
</html>

templates/page/footer.html
{% load static  %}
<!-- Footer 2 - Bootstrap Brain Component -->
<footer class="footer bg-vino text-white">

  <!-- Widgets - Bootstrap Brain Component -->
  <section class="py-4 py-md-5 py-xl-8 border-top border-light text-white">
    <div class="container overflow-hidden">
      <div class="row gy-4 gy-lg-0 justify-content-xl-between">
        <div class="col-12 col-md-4 col-lg-3 col-xl-2">
          <div class="widget">
            <a href="#!">
              <img src="/media/71RFvyqb7nL._AC_SL1500_.jpg" alt="Cheff Tony" width="175" height="auto">
            </a>
          </div>
        </div>
        <div class="col-12 col-md-4 col-lg-3 col-xl-2 text-white">
          <div class="widget">
            <h4 class="widget-title mb-4">Contacto</h4>
            <address class="mb-4">Avenida de Zumalacárregui, San Sebastián</address>
            <p class="mb-1">
              <a class="link-light text-decoration-none" href="tel:+34611576896">611576896</a>
            </p>
            <p class="mb-0">
              Puedes contactar en:
              <a class="link-light text-decoration-none" href="mailto:eabilleira1@protonmail.com">eabilleira1@protonmail.com</a>
            </p>
          </div>
        </div>
        <div class="col-12 col-md-4 col-lg-3 col-xl-2">
          <div class="widget">
            <h4 class="widget-title mb-4">Enlaces de interés</h4>
            <ul class="list-unstyled text-white">
              <li class="mb-2">
                <a href="#!" class="link-light text-decoration-none">Sobre nosotros</a>
              </li>
              <li class="mb-2">
                <a href="#!" class="link-light text-decoration-none">Contacto</a>
              </li>
              <li class="mb-2">
                <a href="{% url 'core:terms_of_use' %}" class="link-light text-decoration-none">Términos de servicio</a>
              </li>
              <li class="mb-0">
                <a href="{% url 'core:privacy_policy' %}" class="link-light text-decoration-none">Política de privacidad</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Copyright - Bootstrap Brain Component -->
  <div class="bg-pan py-4 py-md-5 py-xl-8 border-top border-light-subtle">
    <div class="container overflow-hidden">
      <div class="row gy-4 gy-md-0">
        <div class="col-xs-12 col-md-7 order-1 order-md-0">
          <div class="copyright text-center text-md-start">
            &copy; 2024. All Rights Reserved.
          </div>
          <div class="text-center text-md-start mt-2 fs-7">
            Desarrollado por <a href="https://egoitzabilleira.es/" class="text-vino">EgoDev</a></div>
        </div>
      </div>
    </div>
  </div>
<!-- Scripts de TermsFeed -->
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){
	dataLayer.push(arguments);
}
gtag('consent', 'default', {
	'ad_storage': 'denied',
	'ad_user_data': 'denied',
	'ad_personalization': 'denied',
	'analytics_storage': 'denied'
});
</script>

<script type="text/plain" cookie-consent="tracking" async src="https://www.googletagmanager.com/gtag/js?id=GTM-NGQB2FGB"></script>
<script type="text/plain" cookie-consent="tracking">
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}

	gtag('js', new Date());
	gtag('config', 'GTM-NGQB2FGB');
</script>

<!-- Cookie Consent by TermsFeed https://www.TermsFeed.com -->
<script type="text/javascript" src="//www.termsfeed.com/public/cookie-consent/4.1.0/cookie-consent.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
      document.addEventListener('DOMContentLoaded', function () {
      cookieconsent.run({"notice_banner_type":"simple",
                        "consent_type":"express",
                        "palette":"light",
                        "language":"es",
                        "page_load_consent_levels":["strictly-necessary"],
                        "notice_banner_reject_button_hide":true,
                        "preferences_center_close_button_hide":false,
                        "page_refresh_confirmation_buttons":false,

      "callbacks": {
        "scripts_specific_loaded": (level) => {
          switch(level) {
            case 'targeting':
            //alert('banner configurado');
              gtag('consent', 'update', {
                'ad_storage': 'granted',
                'ad_user_data': 'granted',
                'ad_personalization': 'granted',
                'analytics_storage': 'granted'
              });
              break;
          }
        }
      },
      "callbacks_force": true,

"website_privacy_policy_url":"https://test.egoitzabilleira.es/politica-privacidad/","website_name":"El recetario"});
});
</script>

<noscript>Free cookie consent management tool by <a href="https://www.termsfeed.com/">TermsFeed</a></noscript>
<!-- End Cookie Consent by TermsFeed https://www.TermsFeed.com -->





<!-- Below is the link that users can use to open Preferences Center to change their preferences. Do not modify the ID parameter. Place it where appropriate, style it as needed. -->

<a href="#" class="text-white" id="open_preferences_center">Actualizar preferencias de cookies</a>

</footer>

templates/page/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" aria-label="Offcanvas navbar large" id="mainNav">
    <div class="container-fluid align-items-start">
      <a class="navbar-brand fs-5" href="{% url 'core:home' %}">El Recetario de Patxi</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
        Menú<span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Menú</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:receta_lista' %}">Recetas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'aparatos:aparatos_lista' %}">Hogar y Cocina</a>
            </li>
          </ul>
          <form class="d-flex mt-3 mt-lg-0 h-5" role="search" action="{% url 'core:receta_search' %}">
            <input class="form-control me-2 form-search search-field" type="search" placeholder="Buscar recetas" aria-label="Search">
          </form>

        <ul class="nav navbar-nav navbar-right ms-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <strong>{{ user.username }}</strong></li>
        <li><a class="nav-link" href="{% url 'account_change_password' %}">Cambiar contraseña</a></li>
        <li class="divider"></li>
        <li><a class="nav-link" href="{% url 'account_logout' %}">Cerrar sesión</a></li>
        </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Iniciar sesión</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Registrarse</a>
        </li>
        {% endif %}
      </ul>

        </div>
      </div>
    </div>
  </nav>