core/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from .sitemap import RecetasSitemap
from aparatos.sitemap import AparatosSitemap

app_name = 'core'

sitemaps ={
    'recetas': RecetasSitemap,
    'aparatos': AparatosSitemap,
    }

urlpatterns = [
    path('', views.home, name='home'),
    path('receta_detalle/<slug:slug>/', views.VistaDetalle.as_view(), name='recetas'),
    path('search/', views.receta_search, name='receta_search'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    path('listado-recetas/', views.VistaLista.as_view(), name='receta_lista'),
    path('terminos-de-uso/', views.TermsOfUseView.as_view(), name='terms_of_use'),
    path('politica-de-privacidad/', views.PrivacidadView.as_view(), name='privacy_policy'),
    path('favorito/agregar/<int:receta_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('favorito/eliminar/<int:receta_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
]

recetas_lukas/urls.py
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from aparatos.sitemap import AparatosSitemap
from core.sitemap import RecetasSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'aparatos': AparatosSitemap,
    'recetas': RecetasSitemap,
}

# # Ensure users go through the allauth workflow when logging into admin.
# admin.site.login = staff_member_required(admin.site.login, login_url='/accounts/login')
# # Run the standard admin set-up.
# admin.autodiscover()

urlpatterns = [
    path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('aparatos/', include('aparatos.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('core.urls')),
    path('', include('django_prometheus.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import os
import uuid

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from django.utils import timezone
from easy_thumbnails.files import get_thumbnailer
from taggit.managers import TaggableManager
from easy_thumbnails.exceptions import InvalidImageFormatError
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from django.contrib.postgres.indexes import GinIndex
from django.utils.text import slugify
from autoslug import AutoSlugField

class Categoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    imagen = models.ImageField(upload_to='categorias', blank=True, null=True)
    def __str__(self):
        return self.nombre

# Create your models here.
class ItemsPagina(models.Model):
    class Status(models.TextChoices):
        CREADO = 'CR', 'Creado'
        PUBLICADO = 'PB', 'Publicado'

    titulo = models.CharField(max_length=250)
    autor = models.CharField(max_length=100, default="Lucas")
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.CREADO)
    imagen = ThumbnailerImageField(upload_to='pasos_pics', blank=True, null=True)
    tags = TaggableManager(blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    slug = AutoSlugField(unique=True, populate_from='titulo')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.titulo)

        if self.imagen:
            try:
                img = Image.open(self.imagen)
                img = img.resize((800, 600))
                # Convertir la imagen a formato JPEG
                buffer = BytesIO()
                img.save(buffer, format='JPEG')
                buffer.seek(0)
                # Sobrescribir la imagen original con la nueva imagen
                self.imagen = ContentFile(buffer.getvalue())
            except Exception as e:
                print(f"Error al procesar la imagen: {e}")
        super().save(*args, **kwargs)

    @property
    def tiempo_total(self):
        tiempo_preparacion_total = self.pasos_set.aggregate(Sum('tiempo_preparacion'))['tiempo_preparacion__sum'] or 0
        tiempo_coccion_total = self.pasos_set.aggregate(Sum('tiempo_coccion'))['tiempo_coccion__sum'] or 0
        tiempo_total_combinado = tiempo_preparacion_total + tiempo_coccion_total
        return tiempo_preparacion_total, tiempo_coccion_total, tiempo_total_combinado
    
    @property
    def imagen_default(self):
        # Devuelve la imagen o la penúltima de pasos si no hay imagen
        if self.imagen:
            return self.imagen.url
        else:
            pasos = self.pasos_set.all()
            if pasos.count() >= 2:  # Verifica si hay al menos 2 pasos
                return pasos[pasos.count() - 2].imagen_paso.url  # Penúltima imagen
            return '/media/default.jpg'  # Ruta a la imagen por defecto si no hay imagen en pasos

    def __str__(self):
        return self.titulo

    class Meta:
        ordering = ['fecha_creacion', 'fecha_modificacion']
        indexes = [
            #models.Index(fields=['titulo'], name='titulo_index', opclasses=['varchar_pattern_ops']),
            models.Index(fields=['-fecha_creacion', 'categoria']),
            GinIndex(fields=['titulo'], name='titulo_gin_index', opclasses=['gin_trgm_ops']),
        ]


class Pasos(models.Model):
    numero = models.IntegerField()
    descripcion = models.TextField()
    imagen_paso = models.ImageField(upload_to='recetas_pics', blank=True, null=True)
    recetas = models.ForeignKey(ItemsPagina, on_delete=models.CASCADE)
    tiempo_preparacion = models.IntegerField()
    tiempo_coccion = models.IntegerField()

    def save(self, *args, **kwargs):
        if self.imagen_paso:
            try:
                # Abrir la imagen original
                img = Image.open(self.imagen_paso)
                img = img.resize((800, 600))  # Redimensionar la imagen si es necesario
                # Convertir la imagen a formato JPEG
                buffer = BytesIO()
                img.save(buffer, format='JPEG')
                buffer.seek(0)
                # Generar un nombre único para la imagen
                filename = os.path.join('recetas_pics', f"{uuid.uuid4()}.jpg")
                # Guardar la imagen en el sistema de archivos
                self.imagen_paso.save(filename, ContentFile(buffer.getvalue()), save=False)
                # Limpiar el buffer
                buffer.close()
            except Exception as e:
                print(f"Error al procesar la imagen: {e}")
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['numero']
        indexes = [
            GinIndex(fields=['descripcion'], name='descripcion_gin_index', opclasses=['gin_trgm_ops']),
        ]


class Ingredientes(models.Model):
    nombre = models.CharField(max_length=1000)
    cantidad = models.CharField(max_length=1000, blank=True)
    recetas = models.ForeignKey(ItemsPagina, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        indexes = [
            GinIndex(fields=['nombre'], name='nombre_gin_index', opclasses=['gin_trgm_ops']),
        ]


class FondosHeaders(models.Model):
    vista = models.CharField(max_length=100, blank=True)
    imagen_fondo = models.ImageField(upload_to='imagenes_fondo/', default='default.jpg')
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Imagen de fondo para {self.vista}'

    def get_imagen_fondo_url(self):
        return self.imagen_fondo.url

    def get_imagen_fondo_url_resized(self):
        imagen = Image.open(self.imagen_fondo)
        imagen_resized = imagen.resize((1920, 1080), Image.ANTIALIAS)
        imagen_resized_path = f'imagenes_fondo_resized/{self.imagen_fondo.name}'
        imagen_resized.save(imagen_resized_path)
        return imagen_resized_path

    class Meta:
        verbose_name = 'Encabezados del sitio'
        verbose_name_plural = 'Encabezados del sitio'

class Favorito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    receta = models.ForeignKey(ItemsPagina, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('usuario', 'receta')  # Evita duplicados

    def __str__(self):
        return f'{self.usuario.username} - {self.receta.titulo}'

core/forms.py
from django import forms
from .models import Categoria, ItemsPagina

class SearchForm(forms.Form):
    query = forms.CharField()

class ItemsPaginaForm(forms.Form):
    categorias = forms.MultipleChoiceField(choices=[], required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = ItemsPagina
        fields = ('categorias',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categorias'].choices = [(c.id, c.nombre) for c in Categoria.objects.all()]

    def filter_recetas(self, queryset):
        categoria = self.cleaned_data.get('categoria')

        if categoria:
            # Filtrar el queryset utilizando el objeto de categoría
            queryset = queryset.filter(categoria=categoria)

        return queryset

core/templates/core/perfil_usuario.html
{% extends "page/base.html" %}
{% load static %}
{% block content %}
<section class="page-section bg-light main-section" id="perfil-usuario">
    <div class="container">
        <div class="text-center main-title">
            <h2 class="text-uppercase main-title main-subtitle">Mi Perfil</h2>
            <h3 class="section-subheading text-muted">Mis Recetas Favoritas</h3>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 d-flex align-items-stretch flex-wrap">
            {% if favoritos %}
                {% for favorito in favoritos %}
                <div class="col d-flex align-items-stretch">
                    <div class="card shadow-sm flex-grow-1">
                        <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ forloop.counter }}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            {% if favorito.receta.imagen %}
                            <img class="img-fluid" src="{{ favorito.receta.imagen.url|slice:":-3" }}" alt="imagen nueva" />
                            {% else %}
                                <img class="img-fluid" src="{% static 'images/default.jpg' %}" alt="imagen predeterminada" />
                            {% endif %}
                        </a>
                        <div class="card-body collapsed">
                            <p class="card-text">{{ favorito.receta.titulo }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-body-secondary mb-3">Tiempo preparación: {{ favorito.receta.tiempo_total.2 }} minutos</small>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'core:recetas' slug=favorito.receta.slug %}" class="btn bg-vino">
                                    Ver receta
                                </a>
                                <button class="btn bg-vino" data-receta-id="{{ favorito.receta.id }}" onclick="toggleFavorito(this)">
                                    Quitar de favoritos
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No tienes recetas favoritas todavía.</p>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

core/templates/core/receta_detalle.html
{% extends "page/base.html" %}
{% load static %}

{% block extrahead %}
{% endblock extrahead %}

{% block header %}
{% include "page/navbar.html" %}
{% endblock header %}
{% block content %}
{% if object.categoria and object.categoria.imagen %}
    <header class="masthead" style="background-image: url('{{ object.categoria.imagen.url }}');">
        <div class="container">
            <div class="masthead-subheading">{{ object.categoria.nombre }}</div>
            <div class="masthead-heading">Es hora de cocinar</div>
        </div>
    </header>
{% else %}
    <header class="masthead" style="background-image: url('{% static 'images/default_header.jpg' %}');">
        <div class="container">
            <div class="masthead-subheading">Categoría no disponible</div>
            <div class="masthead-heading">Es hora de cocinar</div>
        </div>
    </header>
{% endif %}
<div class="container">
    <div class="divider"></div>
    <h1 class="receta-title">{{ object.titulo }}</h1>
    <img src="{{ object.imagen_default }}" alt="Image" class="receta-thumbnail">
    <div class="receta-entry">
        <h3 class="receta-title mt-5">Descripción</h3>
        <p class="receta-contenido" id="receta-contenido">{{ object.contenido }}</p>
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-4">Ingredientes:</h5>
                <ul>
                    {% for ingrediente in object.ingredientes_set.all %}
                        <li>{{ ingrediente.nombre }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h5 class="mb-4">Tiempo Total:</h5>
                <ul>
                    <li>Tiempo de Preparación: {{ object.tiempo_total.0 }} minutos</li>
                    <li>Tiempo de Cocción: {{ object.tiempo_total.1 }} minutos</li>
                    <li>Tiempo Total Combinado: {{ object.tiempo_total.2 }} minutos</li>
                </ul>
            </div>
        </div>
        </div>

            {% for paso in object.pasos_set.all %}
                <div class="receta-entry">
                    <h3 class="encabezado-pasos">Paso número {{ paso.numero}}</h3>
                {% if paso.imagen_paso %}
                    <a href="{{ paso.imagen_paso.url }}" class="thumbnail-grande">
                        <img src="{{ paso.imagen_paso.url }}" alt="Image" class="thumbnail-grande">
                    </a>
                {% endif %}
                    <div class="post-content-entry">
                        <p class="paso-descripcion">{{ paso.descripcion }}</p>
                        <p>Tiempo de preparación: {{ paso.tiempo_preparacion }} minutos</p>
                        <p>Tiempo de cocción: {{ paso.tiempo_coccion }} minutos</p>
                    </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="blog-section">
        <div class="container">
            <div id="carouselExampleAutoplaying1" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for receta in recetas_recomendadas %}
                        {% if forloop.first or forloop.counter0|divisibleby:2 %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <div class="row">
                        {% endif %}
                        <div class="col-12 col-sm-6 mb-5">
                            <div class="post-entry">
                                <a href="#" class="post-thumbnail">
                                    <img src="{% if receta.imagen %}{{ receta.imagen.url }}{% else %}{% with receta.pasos_set.all|slice:":-1" as pasos %}{% if pasos|length > 0 %}{{ pasos.last.imagen_paso.url }}{% else %}{% static 'images/default_receta.jpg' %}{% endif %}{% endwith %}{% endif %}" alt="Image" class="img-fluid">
                                </a>
                                <div class="post-content-entry">
                                    <h3><a href="#">{{ receta.titulo }} vista: {{ receta.num_vistas }}</a></h3>
                                    <p>{{ receta.contenido }}</p>
                                    <div class="meta">
                                        <a href="{% url 'core:recetas' slug=receta.slug %}">Ver detalles</a>
                                        <span>Hecha por<a href="#">{{ receta.autor }}</a></span>
                                        <span>el <a href="#">{{ receta.fecha_modificacion }}</a></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if forloop.last or forloop.counter0|add:1|divisibleby:2 %}
                                </div><!--/.row-->
                            </div><!--/.carousel-item-->
                        {% endif %}
                    {% endfor %}
                    {% if recetas_recomendadas|length|divisibleby:2 %}
                        <!-- Agregar un div vacío para rellenar el espacio -->
                        <div class="col-12 col-sm-6 mb-5"></div>
                    {% endif %}
                </div><!--/.carousel-inner-->
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying1" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying1" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="">Next</span>
                </button>
            </div><!--/#carouselExampleAutoplaying-->
        </div><!--/.container-->
    </div><!--/.blog-section-->
    
{% endblock content %}
{% block footer %}
{% include "page/footer.html" %}
{% endblock footer %}

core/templates/core/receta_lista.html
{% extends "page/base.html" %}
{% load static %}

{% block extrahead %}
{% endblock extrahead %}

{% block header %}
<script src="{% static 'js/scripts.js' %}"></script>
{% include "page/navbar.html" %}
{% endblock header %}

{% block content %}
    <header class="masthead" style="background-image: url('{{ imagen_fondo.url }}')">
        <div class="container">
            <div class="masthead-subheading">Bienvenidos al recetario</div>
            <div class="masthead-heading">Es hora de cocinar</div>
        </div>
    </header>
<div class="form-container">
    <form method="GET" class="filtro-form">
        <select name="categorias" class="filtro-select">
            <option value="" class="filtro-option">Todas las categorías</option>
            {% for categorias_id, categorias_nombre in form.fields.categorias.choices %}
                <option value="{{ categorias_id }}" class="filtro-option">{{ categorias_nombre|title }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="filtro-button">Filtrar</button>
    </form>
</div>

<div class="blog-section">
  <div class="container">
      <div class="row">
          {% for receta in recetas %}
          <div class="col-12 col-sm-6 col-md-4 mb-5">
              <div class="post-entry">
                  <a href="{% url 'core:recetas' slug=receta.slug %}" class="post-thumbnail">
                      <img src="{{ receta.imagen_default }}" alt="Image" class="img-fluid">
                  </a>

                  <div class="post-content-entry">
                      <h3><a href="#">{{ receta.titulo }}</a></h3>
                      <p>{{ receta.contenido }}</p>
                      <div class="meta">
                          <a href="{% url 'core:recetas' slug=receta.slug %}">Ver detalles</a>
                          <span class="text-verdura">Hecha por<a href="#">{{ receta.autor }}</a></span>
                          <span>el <a href="#">{{ receta.fecha_creacion }}</a></span>
                      </div>
                  </div>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page=1" aria-label="Primera">
        <span aria-hidden="true">&laquo; Primera</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.previous_page_number }}" aria-label="Previa">
        <span aria-hidden="true">Previa</span>
      </a>
    </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link current">
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
      </span>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
        <span aria-hidden="true">Siguiente</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
        <span aria-hidden="true">Última &raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>


{% endblock content %}

{% block footer %}
{% include 'page/footer.html' %}
{% endblock footer %}

core/templates/core/receta_search.html
{% extends "page/base.html" %}

{% block content %}
    <h1>Resultados de la búsqueda</h1>

    {% if results %}
        <h2>Recetas encontradas</h2>
        <ul>
            {% for result in results %}
                <li>
                    <a href="{% url 'core:recetas' result.slug %}">{{ result.titulo }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No se encontraron recetas.</p>
    {% endif %}
{% endblock %}

core/templates/core/recetas_parcial.html
{% load static %}
{% for item in recetas %}
<div class="col d-flex align-items-stretch">
    <div class="card shadow-sm flex-grow-1">
        <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ forloop.counter }}">
            <div class="portfolio-hover">
                <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
            </div>
            <img class="img-fluid" src="{{ item.imagen_default }}" alt="imagen nueva" />

        </a>
        <div class="card-body collapsed">
            <p class="card-text">{{ item.titulo }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-body-secondary mb-3">Tiempo preparación: {{ item.tiempo_total.2 }} minutos</small>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'core:recetas' slug=item.slug %}" class="btn bg-vino">Ver receta</a>
                <a href="#portfolioModal{{ forloop.counter }}" class="btn bg-vino" data-bs-toggle="modal">Ampliar</a>
                <button class="btn bg-vino" data-receta-id="{{ item.id }}" 
                onclick="toggleFavorito(this)">
                {% if item in request.user.favorito_set.all %}
                Quitar de favoritos
                {% else %}
                Agregar a favoritos
                {% endif %}
            </button>
            </div>
        </div>
    </div>
</div>
{% endfor %}

core/templates/core/terminos_de_uso.html
{% extends 'page/base.html' %}
<body class="terms-page">
{% block header %}
{% include 'page/navbar.html' %}
{% endblock header %}

{% block content %}
    <div class="terms-content">
    <h1 class="terms">1. Introducción</h1>
    <p class="text">Las presentes condiciones generales de uso de la página web, regulan los términos y condiciones de acceso y uso de <a href="www.egoitzabilleira.es">www.egoitzabilleira.es</a>, propiedad de Soluciones Abilleira, con domicilio en Calle Batuecas 20, Salamanca y con Código de Identificación Fiscal número 2023C3693900225K, en adelante, «la Empresa», que el usuario del Portal deberá de leer y aceptar para usar todos los servicios e información que se facilitan desde el portal. El mero acceso y/o utilización del portal, de todos o parte de sus contenidos y/o servicios significa la plena aceptación de las presentes condiciones generales de uso.</p>
    <h1 class="terms">2. Condiciones de uso</h1>
    <p class="text">Las presentes condiciones generales de uso del portal regulan el acceso y la utilización del portal, incluyendo los contenidos y los servicios puestos a disposición de los usuarios en y/o a través del portal, bien por el portal, bien por sus usuarios, bien por terceros. No obstante, el acceso y la utilización de ciertos contenidos y/o servicios puede encontrarse sometido a determinadas condiciones específicas.</p>

    <h1 class="terms">3. Modificaciones</h1>
    <p class="text">La empresa se reserva la facultad de modificar en cualquier momento las condiciones generales de uso del portal. En todo caso, se recomienda que consulte periódicamente los presentes términos de uso del portal, ya que pueden ser modificados.</p>

    <h1 class="terms">4. Obligaciones del Usuario</h1>
    <p class="text">El usuario deberá respetar en todo momento los términos y condiciones establecidos en las presentes condiciones generales de uso del portal. De forma expresa el usuario manifiesta que utilizará el portal de forma diligente y asumiendo cualquier responsabilidad que pudiera derivarse del incumplimiento de las normas. Así mismo, el usuario no podrá utilizar el portal para transmitir, almacenar, divulgar promover o distribuir datos o contenidos que sean portadores de virus o cualquier otro código informático, archivos o programas diseñados para interrumpir, destruir o perjudicar el funcionamiento de cualquier programa o equipo informático o de telecomunicaciones.</p>

    <h1 class="terms">5. Responsabilidad del portal</h1>
    <p class="text">El usuario conoce y acepta que el portal no otorga ninguna garantía de cualquier naturaleza, ya sea expresa o implícita, sobre los datos, contenidos, información y servicios que se incorporan y ofrecen desde el Portal. Exceptuando los casos que la Ley imponga expresamente lo contrario, y exclusivamente con la medida y extensión en que lo imponga, el Portal no garantiza ni asume responsabilidad alguna respecto a los posibles daños y perjuicios causados por el uso y utilización de la información, datos y servicios del Portal. En todo caso, el Portal excluye cualquier responsabilidad por los daños y perjuicios que puedan deberse a la información y/o servicios prestados o suministrados por terceros diferentes de la Empresa. Toda responsabilidad será del tercero ya sea proveedor o colaborador.</p>

    <h1 class="terms">6. Propiedad intelectual e industrial</h1>
    <p class="text">Todos los contenidos, marcas, logos, dibujos, documentación, programas informáticos o cualquier otro elemento susceptible de protección por la legislación de propiedad intelectual o industrial, que sean accesibles en el portal corresponden exclusivamente a la empresa o a sus legítimos titulares y quedan expresamente reservados todos los derechos sobre los mismos. Queda expresamente prohibida la creación de enlaces de hipertexto (links) a cualquier elemento integrante de las páginas web del Portal sin la autorización de la empresa, siempre que no sean a una página web del Portal que no requiera identificación o autenticación para su acceso, o el mismo esté restringido. En cualquier caso, el portal se reserva todos los derechos sobre los contenidos, información datos y servicios que ostente sobre los mismos. El portal no concede ninguna licencia o autorización de uso al usuario sobre sus contenidos, datos o servicios, distinta de la que expresamente se detalle en las presentes condiciones generales de uso del portal.</p>

    <h1 class="terms">7. Legislación aplicable, jurisdicción competente y notificaciones</h1>
    <p class="text">Las presentes condiciones se rigen y se interpretan de acuerdo con las Leyes de España. Para cualquier reclamación serán competentes los juzgados y tribunales de Salamanca. Todas las notificaciones, requerimientos, peticiones y otras comunicaciones que el Usuario desee efectuar a la Empresa titular del Portal deberán realizarse por escrito y se entenderá que han sido correctamente realizadas cuando hayan sido recibidas en la siguiente dirección <a href="mailto:meimportaunamierda@protonmail.com">meimportaunamierda@protonmail.com</a>.</p>
    </div>
{% endblock %}

{% block footer %}
{% include "page/footer.html" %}
{% endblock footer %}
</body>