aparatos/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from .sitemap import AparatosSitemap


app_name = 'aparatos'

sitemaps ={
    'aparatos': AparatosSitemap,
    }

urlpatterns = [
    path('lista/', views.ListaAparatos.as_view(), name='aparatos_lista'),
    path('producto-detalle/<slug:slug>', views.DetalleAparatos.as_view(), name='aparatos_detalle'),
    path('modelo-detalle/<slug:slug>', views.DetalleModelo.as_view(), name='modelo_detalle'),
]

core/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
from .sitemap import RecetasSitemap
from aparatos.sitemap import AparatosSitemap

app_name = 'core'

sitemaps ={
    'recetas': RecetasSitemap,
    'aparatos': AparatosSitemap,
    }

urlpatterns = [
    path('', views.home, name='home'),
    path('receta_detalle/<slug:slug>/', views.VistaDetalle.as_view(), name='recetas'),
    path('search/', views.receta_search, name='receta_search'),
    path('autocomplete/', views.AutocompleteView.as_view(), name='autocomplete'),
    path('listado-recetas/', views.VistaLista.as_view(), name='receta_lista'),
    path('terminos-de-uso/', views.TermsOfUseView.as_view(), name='terms_of_use'),
    path('politica-de-privacidad/', views.PrivacidadView.as_view(), name='privacy_policy'),
    path('favorito/agregar/<int:receta_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('favorito/eliminar/<int:receta_id>/', views.eliminar_favorito, name='eliminar_favorito'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
]

recetas_lukas/urls.py
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from aparatos.sitemap import AparatosSitemap
from core.sitemap import RecetasSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'aparatos': AparatosSitemap,
    'recetas': RecetasSitemap,
}

# # Ensure users go through the allauth workflow when logging into admin.
# admin.site.login = staff_member_required(admin.site.login, login_url='/accounts/login')
# # Run the standard admin set-up.
# admin.autodiscover()

urlpatterns = [
    path('admin/defender/', include('defender.urls')), # defender admin
    path('admin/', admin.site.urls),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('aparatos/', include('aparatos.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('', include('core.urls')),
    path('', include('django_prometheus.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aparatos/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from django.utils.text import slugify
from autoslug import AutoSlugField
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from taggit.managers import TaggableManager


class Categoria(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    imagen = models.ImageField(upload_to='categorias_recetas', blank=True, null=True)
    def __str__(self):
        return self.nombre


class Aparatos(models.Model):
    class Status(models.TextChoices):
        CREADO = 'CR', 'Creado'
        PUBLICADO = 'PB', 'Publicado'

    nombre = models.CharField(max_length=250)
    descripcion = models.TextField()
    usos = models.TextField()
    caracteristica_generales = models.TextField()
    imagen = ThumbnailerImageField(upload_to='pasos_pics', blank=True, null=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.CREADO)
    slug = AutoSlugField(unique=True, populate_from='nombre')
    tags = TaggableManager(blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    link_amazon = models.URLField(blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nombre)

        if self.imagen:
            try:
                img = Image.open(self.imagen)
                img = img.resize((800, 600))
                # Convertir la imagen a formato JPEG
                buffer = BytesIO()
                img.save(buffer, format='JPEG')
                buffer.seek(0)
                # Sobrescribir la imagen original con la nueva imagen
                self.imagen = InMemoryUploadedFile(buffer, None, 'imagen.jpg', 'image/jpeg', buffer.getbuffer().nbytes, None)
            except Exception as e:
                print(f"Error al procesar la imagen: {e}")
        super().save(*args, **kwargs)

    def imagen_categoria_url(self):
            return self.categoria.imagen.url if self.categoria.imagen else None


class Modelos(models.Model):
    class Status(models.TextChoices):
        CREADO = 'CR', 'Creado'
        PUBLICADO = 'PB', 'Publicado'

    nombre = models.CharField(max_length=255)
    modelo = models.ForeignKey(Aparatos, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='aparatos_likes', blank=True)
    link_amazon = models.URLField(blank=True)
    caracteristicas_modelo = models.TextField()
    año = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.CREADO)
    imagen = ThumbnailerImageField(upload_to='pasos_pics', blank=True, null=True)
    slug = AutoSlugField(unique=True, populate_from='nombre')
    tags = TaggableManager(blank=True)
    fecha_modificacion = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            # Generar el slug basado en el nombre del aparato y del modelo
            self.slug = slugify(f"{self.modelo.nombre}-{self.nombre}")

        # Resto de la lógica del método save
        super().save(*args, **kwargs)

        if self.imagen:
            try:
                img = Image.open(self.imagen)
                img = img.resize((800, 600))
                # Convertir la imagen a formato JPEG
                buffer = BytesIO()
                img.save(buffer, format='JPEG')
                buffer.seek(0)
                # Sobrescribir la imagen original con la nueva imagen
                self.imagen = InMemoryUploadedFile(buffer, None, 'imagen.jpg', 'image/jpeg', buffer.getbuffer().nbytes, None)
            except Exception as e:
                print(f"Error al procesar la imagen: {e}")
        super().save(*args, **kwargs)

aparatos/forms.py
from django import forms
from .models import Aparatos, Categoria


class AparatosForm(forms.ModelForm):
    categorias = forms.MultipleChoiceField(choices=[], required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Aparatos
        fields = ('categorias',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categorias'].choices = [(c.id, c.nombre) for c in Categoria.objects.all()]

    def filter(self, queryset):  # Cambia el nombre del método de filter_recetas a filter
        categoria = self.cleaned_data.get('categorias')

        if categoria:
            queryset = queryset.filter(categoria=categoria)

        return queryset

aparatos/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from .models import Aparatos, Modelos
from core.models import FondosHeaders
from .forms import AparatosForm
# Create your views here.

class ListaAparatos(ListView):
    model = Aparatos
    template_name = 'aparatos/aparatos_lista.html'
    context_object_name = 'aparatos'
    paginate_by = 9

    def get_queryset(self):
        queryset = Aparatos.objects.filter(status='CR').order_by('categoria')
        form = AparatosForm(self.request.GET)
        if form.is_valid():
            categorias_selected = form.cleaned_data.get('categorias')
            if categorias_selected:
                queryset = queryset.filter(categoria__in=categorias_selected)
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            imagen_fondo = cache.get_or_set('imagen_fondo_lista_aparatos', FondosHeaders.objects.get(vista="aparatos_lista").imagen_fondo, timeout=6)
        except ObjectDoesNotExist:
            # Si el objeto FondosHeaders no existe, proporciona un valor predeterminado o maneja la excepción de otra manera
            imagen_fondo = '/var/www/WebRecetas/media/imagenes_fondo/kitchen-2400367_1920.jpg'
        context['form'] = AparatosForm(self.request.GET)
        context['imagen_fondo'] = imagen_fondo
        return context

class DetalleAparatos(DetailView):
    model = Aparatos
    template_name = 'aparatos/aparatos_detalle.html'
    context_object_name = 'aparatos'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            imagen_fondo = cache.get_or_set('imagen_fondo_detalle_aparatos', FondosHeaders.objects.get(vista="aparatos_detalle").imagen_fondo, timeout=6)
        except ObjectDoesNotExist:
            # Si el objeto FondosHeaders no existe, proporciona un valor predeterminado o maneja la excepción de otra manera
            imagen_fondo = '/home/felipe/Recetas/media/imagenes_fondo/kitchen-2400367_1920.jpg'  # Cambia esto por la ruta de tu imagen predeterminada
        context['imagen_fondo'] = imagen_fondo
        return context


class DetalleModelo(DetailView):
    model = Modelos
    template_name = 'aparatos/modelos_detalle.html'
    context_object_name = 'modelos'

aparatos/templates/aparatos/aparatos_detalle.html
{% extends "page/base.html" %}
{% load static %}

{% block extrahead %}
{% endblock extrahead %}

{% block header %}
{% include "page/navbar.html" %}
{% endblock header %}

{% block content %}
<header class="masthead" style="background-image: url('{{ imagen_fondo.url }}')">
    <div class="container">
        <div class="masthead-subheading text-pan">Hogar y cocina</div>
        <div class="masthead-heading text-pan">Compra y descubre aparatos y herramientas</div>
    </div>
</header>
<div class="recipe-detail container">
    <h1 class="receta-title">{{ object.nombre }}</h1>
    {% if object.imagen %}
        <img class="receta-thumbnail"src="{{ object.imagen.url }}" alt="{{ object.nombre }}">
    {% else %}
    {% endif %}
    <div class="receta-entry">
    <h3 class="receta-title mt-5">Descripción</h3>
    {% if object.descripcion %}
    <p class="receta-contenido" id="receta-contenido">Descripción: {{ object.descripcion }}</p>
    {% endif %}
    {% if object.usos %}
    <h3 class="receta-title mt-5">Usos</h3>
    <p class="receta-contenido" id="receta-contenido">Usos: {{ object.usos }}</p>
    {% endif %}
    {% if object.caracteristica_generales %}
    <h3 class="receta-title mt-5">Características</h3>
    <p class="receta-contenido" id="receta-contenido">Características: {{ object.caracteristica_generales }}</p>
    {% endif %}
    {% if object.modelos_set.all %}
        <h2 class="mt-4">Modelos asociados:</h2>
        <ul>
    {% for modelo in object.modelos_set.all %}
        <li class="text-pan"><a href="{% url 'aparatos:modelo_detalle' modelo.slug %}" class="text-vino">{{ modelo.nombre }}</a></li>
            <span><a href="{{ modelo.link_amazon }}" target="_blank" >
            <button class="amazon-button">Comprar en Amazon</button></a></span>
    {% endfor %}
        </ul>
    {% endif %}
</div>
</div>
{% endblock content %}

{% block footer %}
{% include 'page/footer.html' %}
{% endblock footer %}

aparatos/templates/aparatos/aparatos_lista.html
{% extends "page/base.html" %}
{% load static %}
{% block extrahead %}
{% endblock extrahead %}

{% block header %}
{% include "page/navbar.html" %}
{% endblock header %}

{% block content %}
<header class="masthead" style="background-image: url('{{ imagen_fondo.url }}')">
    <div class="container">
        <div class="masthead-subheading">Hogar y cocina</div>
        <div class="masthead-heading">Compra y descubre aparatos y herramientas</div>
    </div>
</header>

<div class="form-container">
<form method="GET" class="filtro-form">
    <select name="categorias" class="filtro-select">
        <option value="" class="filtro-option">Todas las categorías</option>
        {% for categorias_id, categorias_nombre in form.fields.categorias.choices %}
            <option value="{{ categorias_id }}" class="filtro-option">{{ categorias_nombre|title }}</option>
        {% endfor %}
    </select>
    <button type="submit" class="filtro-button">Filtrar</button>
</form>
</div>

<div class="blog-section">
    <div class="container">
        <div class="row">
            {% for receta in object_list %}
                <div class="col-12 col-sm-6 col-md-4 mb-5">
                    <div class="post-entry">
                        <a href="#" class="post-thumbnail">
                        <img src="{% if receta.imagen %}{{ receta.imagen.url }}{% else %}/media/alubias.jpeg.800x600_q85_crop.jpg{% endif %}" alt="Image" class="img-fluid"></a>
                        <div class="post-content-entry">
                            <h3><a href="#">{{ receta.nombre }}</a></h3>
                            <p>{{ receta.descripcion }}</p>
                            <div class="meta">
                                <a href="{% url 'aparatos:aparatos_detalle' slug=receta.slug %}">Ver detalles</a>
                                <span><a href="{{ receta.link_amazon }}" target="_blank" >
                                  <button class="amazon-button">Comprar en Amazon</button>
                                  </a>
                                </span>
                            </div>
                        </div>
                        <h3 class="mt-5 mb-3">Modelos Asociados:</h3>
                        <ul>
                            {% for modelo in receta.modelos_set.all %}
                                <li class="text-pan"><a class="text-vino" href="{% url 'aparatos:modelo_detalle' modelo.slug %}">{{ modelo.nombre }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<nav aria-label="Page navigation example">
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page=1" aria-label="Primera">
        <span aria-hidden="true">&laquo; Primera</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.previous_page_number }}" aria-label="Previa">
        <span aria-hidden="true">Previa</span>
      </a>
    </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link current">
        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
      </span>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
        <span aria-hidden="true">Siguiente</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link pagination-button-separate" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
        <span aria-hidden="true">Última &raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock content %}

{% block footer %}
{% include 'page/footer.html' %}
{% endblock footer %}

aparatos/templates/aparatos/modelos_detalle.html
{% extends "page/base.html" %}
{% load static %}
{% block extrahead %}
{% endblock extrahead %}
{% block header %}
{% include "page/navbar.html" %}
{% endblock header %}
{% block content %}
<header class="masthead" style="background-image: url('{{ object.modelo.imagen.url }}')">
    <div class="container">
        <div class="masthead-subheading">{{ object.modelo.categoria.nombre}}</div>
        <div class="masthead-heading">Compra y descubre aparatos y herramientas</div>
    </div>
</header>
<!-- Detalles del objeto específico (receta o aparato) -->
<div class="recipe-detail container">
    <div class="divider"></div>
        <h1 class="receta-title">{{ object.nombre }}</h1>
        {% if object.imagen %}
            <img src="{{ object.imagen.url }}" alt="{{ object.nombre }}" class="receta-thumbnail">
        {% else %}
            <p>No hay imagen disponible</p>
        {% endif %}
    <div class="receta-entry">
            <h3 class="receta-title mt-5">Descripción</h3>
        {% if object.modelo.descripcion %}
            <p class="receta-contenido" id="receta-contenido">{{ object.modelo.descripcion }}</p>
        {% endif %}
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-4">Usos:</h5>
            {% if object.modelo.usos %}
                <p class="receta-contenido">Usos: {{ object.modelo.usos }}</p>
            {% endif %}
            </div>
            <div class="col-md-6">
                <h5 class="mb-4">Características modelo:</h5>
                {% if object.caracteristicas_modelo %}
                <p class="receta-contenido">Características modelo: {{ object.caracteristicas_modelo }}</p>
                <p class="receta-contenido">Año modelo: {{ object.año }}</p>
                {% endif %}
            </div>
            <div class="col-md-6">
                {% if object.link_amazon %}
                <a href="{{ object.link_amazon }}" target="_blank" class="receta-contenido">
                <button class="amazon-button">Comprar en Amazon</button>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block footer %}
{% include 'page/footer.html' %}
{% endblock footer %}